export const ADD_NEW_REVIEW_REQUEST = "ADD_NEW_REVIEW_REQUEST";
export const ADD_NEW_REVIEW_SUCCESS = "ADD_NEW_REVIEW_SUCCESS";
export const ADD_NEW_REVIEW_FAILURE = "ADD_NEW_REVIEW_FAILURE";

export const GET_ALL_REVIEWS_REQUEST="GET_ALL_REVIEWS_REQUEST";
export const GET_ALL_REVIEWS_SUCCESS="GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_FAILURE="GET_ALL_REVIEWS_FAILURE";


export const DELETE_REVIEW_REQUEST="DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS="DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE="DELETE_REVIEW_FAILURE";