export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_FAILURE = "GET_SINGLE_ORDER_FAILURE";

export const GET_ALL_ADMIN_ORDER_REQUEST = "GET_ALL_ADMIN_ORDER_REQUEST";
export const GET_ALL_ADMIN_ORDER_SUCCESS = "GET_ALL_ADMIN_ORDER_SUCCESS";
export const GET_ALL_ADMIN_ORDER_FAILURE = "GET_ALL_ADMIN_ORDER_FAILURE";

export const UPDATE_ADMIN_ORDER_STATUS_REQUEST = "UPDATE_ADMIN_ORDER_STATUS_REQUEST";
export const UPDATE_ADMIN_ORDER_STATUS_SUCCESS = "UPDATE_ADMIN_ORDER_STATUS_SUCCESS";
export const UPDATE_ADMIN_ORDER_STATUS_FAILURE = "UPDATE_ADMIN_ORDER_STATUS_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";