export const GET_PRODUCT_DATA_REQUEST = "GET_PRODUCT_DATA_REQUEST";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_ORDER_FAILURE";

export const GET_ADMIN_PRODUCTS_REQUEST = "GET_ADMIN_PRODUCTS_REQUEST";
export const GET_ADMIN_PRODUCTS_SUCCESS = "GET_ADMIN_PRODUCTS_SUCCESS";
export const GET_ADMIN_PRODUCTS_FAILURE = "GET_ADMIN_PRODUCTS_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST ="UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS ="UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE ="UPDATE_PRODUCT_FAILURE";

export const CREATE_NEW_PRODUCT_REQUEST ="CREATE_NEW_PRODUCT_REQUEST";
export const CREATE_NEW_PRODUCT_SUCCESS ="CREATE_NEW_PRODUCT_SUCCESS";
export const CREATE_NEW_PRODUCT_FAILURE ="CREATE_NEW_PRODUCT_FAILURE";