export const ADD_PRODUCT_IN_CART_REQUEST = "ADD_PRODUCT_IN_CART_REQUEST";
export const ADD_PRODUCT_IN_CART_SUCCESS = "ADD_PRODUCT_IN_CART_SUCCESS";
export const ADD_PRODUCT_IN_CART_FAILURE = "ADD_PRODUCT_IN_CART_FAILURE";

