export const ADD_PRODUCT_IN_CART_REQUEST = "ADD_PRODUCT_IN_CART_REQUEST";
export const ADD_PRODUCT_IN_CART_SUCCESS = "ADD_PRODUCT_IN_CART_SUCCESS";
export const ADD_PRODUCT_IN_CART_FAILURE = "ADD_PRODUCT_IN_CART_FAILURE";

export const REMOVE_PRODUCT_FROM_CART_REQUEST = "REMOVE_PRODUCT_FROM_CART_REQUEST";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS";
export const REMOVE_PRODUCT_FROM_CART_FAILURE = "REMOVE_PRODUCT_FROM_CART_FAILURE";

export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILURE = "SAVE_PRODUCT_FAILURE";